---
title: ciptamedia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
gems:
- jekyll-archives
- jekyll-sitemap
- jekyll-paginate
exclude:
- "/vendor/"
subtitle: A simple yet classy theme for your Jekyll website or blog
email: blcentra@gmail.com
name: Ben Centra
description: 'A simple yet classy theme for your Jekyll website or blog.

'
baseurl: "/ciptamedia"
url: http://riosatria.github.io
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: monokai_sublime
jekyll-archives:
  enabled:
  - categories
  - tags
  layout: archive
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
- cat: dummy
  desc: Just some placeholder posts, lorem ipsum and the rest.
social:
- name: Twitter
  icon: twitter
  username: TheBenCentra
  url: https://twitter.com/TheBenCentra
  desc: Follow me on Twitter
  share: true
- name: Facebook
  icon: facebook
  username: thebencentra
  url: 
  desc: Friend me on Facebook
  share: true
- name: GitHub
  icon: github
  username: bencentra
  url: https://github.com/bencentra
  desc: Fork me on GitHub
  share: false
- name: LinkedIn
  icon: linkedin
  username: Ben Centra
  url: https://www.linkedin.com/pub/ben-centra/47/769/60a
  desc: Connect with me on LinkedIn
  share: true
- name: Google+
  icon: google-plus
  username: 
  url: 
  desc: Add me to your Circles
  share: true
- name: YouTube
  icon: youtube
  username: 
  url: 
  desc: Subscribe on YouTube
  share: false
- name: Instagram
  icon: instagram
  username: 
  url: 
  desc: Follow me on Instagram
  share: false
- name: Pinterest
  icon: pinterest
  username: 
  url: 
  desc: Follow me on Pinterest
  share: true
- name: SoundCloud
  icon: soundcloud
  username: 
  url: 
  desc: Follow me on SoundCloud
  share: false
- name: Tumblr
  icon: tumblr
  username: 
  url: 
  desc: Follow me on Tumblr
  share: false
- name: Steam
  icon: steam
  username: 
  url: 
  desc: Friend me on Steam
  share: false
- name: Dribbble
  icon: dribbble
  username: 
  url: 
  desc: Follow me on Dribble
  share: false
- name: Vimeo
  icon: vimeo-square
  username: 
  url: 
  desc: Follow me on Vimeo
  share: false
- name: Vine
  icon: vine
  username: 
  url: 
  desc: Follow me on Vine
  share: false
- name: Reddit
  icon: reddit
  username: 
  url: 
  desc: Share to Reddit
  share: true
- name: Hacker News
  icon: hacker-news
  username: 
  url: 
  desc: Share to Hacker News
  share: false
protocols:
  fb_image: "/assets/logo.png"
  fb_image_width: 612
  fb_image_height: 605
  fb_image_type: image/png
  twitter_image: "/assets/logo.png"
  os_repo: https://github.com/bencentra/centrarium.com
  os_rcs_type: git
  os_src: git@github.com:bencentra/centrarium.com.git
